{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "747e3ba1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Hi! I am a chatbot created by saurabh trivedi for your service\n",
      ">hi\n",
      "Hey there\n",
      ">my name is saurabh \n",
      "Hello saurabh , How are you today ?\n",
      ">fine\n",
      "Great to hear that, How can I help you?\n",
      ">what is yoyu name\n",
      "I am a bot, created by Saurabh Trivedi. you can call me booty or jarvis!\n",
      ">sorry\n",
      "Its OK, never mind\n",
      ">how are you\n",
      "Thanks for asking me, I'm doing good and what about You ?\n",
      ">fine\n",
      "Great to hear that, How can I help you?\n",
      ">what is your age\n",
      "I am a computer program dude and Seriously you are asking me this?\n",
      ">what you want\n",
      "Make me an offer I can not refuse\n",
      ">who created you\n",
      "Trivedi created me using Python's NLTK library \n",
      ">what is your location\n",
      "Seriously dude; you asking me that, BTW now I am in your computer.\n",
      ">how is weather in DELHI\n",
      "Too hot man here in delhi\n",
      ">i work in trulymadly\n",
      "trulymadly is an Amazing company, I have heard about it. But they are in huge loss these days.\n",
      ">is raining in bihar\n",
      "Damn its raining too much here in bihar\n",
      ">how is your health\n",
      "I'm a computer program, so I'm always healthy \n",
      ">which sports do you like\n",
      "I'm a very big fan of circket\n",
      ">which game do you like\n",
      "I'm a very big fan of circket\n",
      ">who is your favorite actor\n",
      "Robert jhonny jr.\n",
      ">who is your favorite movies star\n",
      "Robert jhonny jr.\n",
      ">thanks\n",
      "I'm honoured to serve :)\n",
      ">thank\n",
      "None\n",
      ">thank you\n",
      "My pleasure :)\n",
      ">thanks for help\n",
      "My pleasure :)\n",
      ">thank for help\n",
      "You're very welcome :) \n",
      ">exit\n",
      "Do you really want to exit if yes then type quit :) \n",
      ">cancel\n",
      "Do you really want to cancel if yes then type quit :) \n",
      ">quit\n",
      "BBye take care. See you soon :) \n"
     ]
    }
   ],
   "source": [
    "import nltk\n",
    "from nltk.chat.util import Chat, reflections\n",
    "\n",
    "\n",
    "reflections = {\n",
    "  \"i am\"       : \"you are\",\n",
    "  \"i was\"      : \"you were\",\n",
    "  \"i\"          : \"you\",\n",
    "  \"i'm\"        : \"you are\",\n",
    "  \"i'd\"        : \"you would\",\n",
    "  \"i've\"       : \"you have\",\n",
    "  \"i'll\"       : \"you will\",\n",
    "  \"my\"         : \"your\",\n",
    "  \"you are\"    : \"I am\",\n",
    "  \"you were\"   : \"I was\",\n",
    "  \"you've\"     : \"I have\",\n",
    "  \"you'll\"     : \"I will\",\n",
    "  \"your\"       : \"my\",\n",
    "  \"yours\"      : \"mine\",\n",
    "  \"you\"        : \"me\",\n",
    "  \"me\"         : \"you\"\n",
    "}\n",
    "\n",
    "\n",
    "\n",
    "pairs = [\n",
    "    [\n",
    "        r\"my name is (.*)\",\n",
    "        [\"Hello %1, How are you today ?\",]\n",
    "    ],\n",
    "    [\n",
    "        r\"hi|hey|hello\",\n",
    "        [\"Hello\", \"Hey there\",]\n",
    "    ], \n",
    "    [\n",
    "        r\"what is your name ?\",\n",
    "        [\"I am a bot, created by Saurabh Trivedi. you can call me booty or jarvis!\",]\n",
    "    ],\n",
    "    [\n",
    "        r\"(.*)name\",\n",
    "        [\"I am a bot, created by Saurabh Trivedi. you can call me booty or jarvis!\",]\n",
    "    ],\n",
    "    [\n",
    "        r\"how are you ?|how'r you|what about you\",\n",
    "        [\"Thanks for asking me, I'm doing good and what about You ?\",]\n",
    "    ],\n",
    "    [\n",
    "        r\"sorry (.*)|sorry\",\n",
    "        [\"Its alright\",\"Its OK, never mind\",]\n",
    "    ],\n",
    "    [\n",
    "        r\"I am fine|i'm fine|fine|great|i'm good|i am good\",\n",
    "        [\"Great to hear that, How can I help you?\",]\n",
    "    ],\n",
    "    [\n",
    "        r\"i am (.*) doing good\",\n",
    "        [\"Nice to hear that\",\"How can I help you?:)\",]\n",
    "    ],\n",
    "    [\n",
    "        r\"(.*) age?\",\n",
    "        [\"I am a computer program dude and Seriously you are asking me this?\",]\n",
    "    ],\n",
    "    [\n",
    "        r\"what (.*) want ?\",\n",
    "        [\"Make me an offer I can not refuse\",]\n",
    "    ],\n",
    "    [\n",
    "        r\"(.*) created ?\",\n",
    "        [\"Trivedi created me using Python's NLTK library \",\"it's top secret ;)\",]\n",
    "    ],\n",
    "    [\n",
    "        r\"(.*) (location|city) ?\",\n",
    "        ['Seriously dude; you asking me that, BTW now I am in your computer.',]\n",
    "    ],\n",
    "    [\n",
    "        r\"how is weather in (.*)?\",\n",
    "        [\"Weather in %1 is awesome like always\",\"Too hot man here in %1\",\"Too cold man here in %1\",\"Never even heard about %1\"]\n",
    "    ],\n",
    "    [\n",
    "        r\"i work in (.*)?\",\n",
    "        [\"%1 is an Amazing company, I have heard about it. But they are in huge loss these days.\",]\n",
    "    ],\n",
    "    [\n",
    "        r\"(.*)raining in (.*)\",\n",
    "        [\"No rain since last week here in %2\",\"Damn its raining too much here in %2\"]\n",
    "    ],\n",
    "    [\n",
    "        r\"how (.*) health(.*)\",\n",
    "        [\"I'm a computer program, so I'm always healthy \",]\n",
    "    ],\n",
    "    [\n",
    "        r\"(.*) (sports|game) ?\",\n",
    "        [\"I'm a very big fan of circket\",]\n",
    "    ],\n",
    "    [\n",
    "        r\"who (.*) sports person ?\",\n",
    "        [\"virat\",\"Ronaldo\",\"messy\"]\n",
    "    ],\n",
    "    [\n",
    "        r\"who (.*) (movies star|actor)?\",\n",
    "        [\"Robert jhonny jr.\"]\n",
    "    ],\n",
    "    [\n",
    "        r\"thanks|thank you|thanks (.*)|thank (.*)\",\n",
    "        [\"You're very welcome :) \",\"Any Time :) \",\"I'm honoured to serve :)\",\"No worries,I'm here to help :)\",\"My pleasure :)\"]\n",
    "    ],\n",
    "    [\n",
    "        r\"exit\",\n",
    "        [\"Do you really want to exit if yes then type quit :) \",\"Seriously you want to exit if yes then type quit :)\"]\n",
    "    ],\n",
    "    [\n",
    "        r\"cancel\",\n",
    "        [\"Do you really want to cancel if yes then type quit :) \",\"Seriously you want to cancel if yes then type quit :)\"]\n",
    "    ],\n",
    "    [\n",
    "        r\"quit\",\n",
    "        [\"BBye take care. See you soon :) \",\"It was nice talking to you. See you soon :)\"]\n",
    "    ],\n",
    "]\n",
    "\n",
    "\n",
    "\n",
    "def chat():\n",
    "    print(\"Hi! I am a chatbot created by saurabh trivedi for your service\")\n",
    "    chat = Chat(pairs, reflections)\n",
    "    chat.converse()\n",
    "\n",
    "#initiate the conversation\n",
    "if __name__ == \"__main__\":\n",
    "    chat()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
